### ISSUE TITLE
github pages config gets lost?

### ISSUE THREAD

**Issue by marc-portier** [arms-mbon/arms-mbon.github.io#2]
for some reason the settings on https://github.com/arms-mbon/data.arms-mbon.org/settings/pages keeps forgetting the domain we have added

**Comment by kmexter** [comment]
so we all remember the temporary fix
go to https://github.com/arms-mbon/arms-mbon.github.io/settings/pages
type data.arms-mbon.org in the Custom Domain section
Wait a bit

**Comment by kmexter** [comment]
potential fix? https://stackoverflow.com/questions/67183664/why-is-my-github-pages-custom-domain-constantly-reset
